# Generated by Django 5.2.17 on 2026-09-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="brand",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
