# Generated by Django 5.2.17 on 2026-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_vault_vacuum"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
