"""Iranian banks: display name, brand colour and logo, for the UI.

Keys of banks we parse SMS for are the parser names (parsers.PARSERS), so SMS accounts get
their logo with no setup; other banks are there to pick for a manual account.

Logos: persianlabs/icons (MIT, see static/ledger/banks/LICENSE), served from our own origin
(strict CSP, and no third-party requests from Iran). Colours come from each logo.
The strict CSP also forbids inline styles, so colours live in static/ledger/banks.css,
generated from this file:  python -m ledger.banks
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Bank:
    key: str
    label: str
    color: str


BANKS: dict[str, Bank] = {b.key: b for b in [
    Bank("melli", "ملی", "#f1af0e"),
    Bank("sepah", "سپه", "#1b5fc1"),
    Bank("mellat", "ملت", "#ba0b22"),
    Bank("tejarat", "تجارت", "#2f4a98"),
    Bank("saderat", "صادرات", "#2d2a68"),
    Bank("keshavarzi", "کشاورزی", "#4a7a2c"),
    Bank("maskan", "مسکن", "#ec520d"),
    Bank("refah", "رفاه کارگران", "#173576"),
    Bank("post", "پست بانک", "#14763e"),
    Bank("saman", "سامان", "#00aae7"),
    Bank("blu", "بلو", "#4e91e6"),
    Bank("pasargad", "پاسارگاد", "#fecc09"),
    Bank("parsian", "پارسیان", "#b27d53"),
    Bank("eghtesad_novin", "اقتصاد نوین", "#662892"),
    Bank("khavarmianeh", "خاورمیانه", "#f29200"),
    Bank("bankino", "بانکینو", "#f68e1e"),
    Bank("shahr", "شهر", "#d8262c"),
    Bank("dey", "دی", "#008b9a"),
    Bank("sina", "سینا", "#277eb5"),
    Bank("sarmayeh", "سرمایه", "#1f1f48"),
    Bank("karafarin", "کارآفرین", "#0c730a"),
    Bank("iranzamin", "ایران زمین", "#4c2a93"),
    Bank("gardeshgari", "گردشگری", "#b11116"),
    Bank("resalat", "قرض‌الحسنه رسالت", "#00bbe6"),
    Bank("mehr_iran", "قرض‌الحسنه مهر ایران", "#209b1c"),
    Bank("sanat_madan", "صنعت و معدن", "#9b814c"),
    Bank("tosee_saderat", "توسعه صادرات", "#006d08"),
    Bank("tosee_taavon", "توسعه تعاون", "#51b5d1"),
    Bank("iran_venezuela", "ایران و ونزوئلا", "#2e3390"),
    Bank("melal", "ملل", "#37389a"),
    Bank("noor", "نور", "#0bbbb9"),
    Bank("caspian", "کاسپین", "#313c4c"),
]}

CHOICES = [("", "بدون لوگو"), *((b.key, b.label) for b in BANKS.values())]
STATIC = Path(__file__).parent / "static" / "ledger"


def get(key: str | None) -> Bank | None:
    return BANKS.get(key or "")


def render_css() -> str:
    rules = "\n".join(f".bk-{b.key} {{ --bk: {b.color}; }}" for b in BANKS.values())
    return f"/* Generated by `python -m ledger.banks` from ledger/banks.py. Do not edit. */\n{rules}\n"


if __name__ == "__main__":
    (STATIC / "banks.css").write_text(render_css())
    missing = [k for k in BANKS if not (STATIC / "banks" / f"{k}.svg").exists()]
    print("wrote banks.css" + (f"; missing logos: {missing}" if missing else ""))
