from django.urls import path

from .views import api, app, auth, me, security, staff

urlpatterns = [
    # public
    path("login/", auth.login_view, name="login"),
    path("login/verify/", auth.login_2fa, name="login_2fa"),
    path("logout/", auth.logout_view, name="logout"),
    path("join/<str:code>/", auth.join, name="join"),
    path("ingest", api.ingest_view, name="ingest"),
    path("healthz", api.healthz, name="healthz"),
    path("metrics", api.metrics, name="metrics"),
    path("manifest.webmanifest", api.manifest, name="manifest"),
    path("sw.js", api.service_worker, name="sw"),
    path("offline/", api.offline, name="offline"),
    # app
    path("", app.home, name="home"),
    path("more/", app.more, name="more"),
    path("inbox/", app.inbox, name="inbox"),
    path("tx/", app.tx_list, name="tx_list"),
    path("tx/export.csv", app.tx_export, name="tx_export"),
    path("tx/new/", app.tx_new, name="tx_new"),
    path("tx/<int:pk>/", app.tx_detail, name="tx_detail"),
    path("tx/<int:pk>/delete/", app.tx_delete, name="tx_delete"),
    path("tx/<int:pk>/category/", app.tx_set_category, name="tx_set_category"),
    path("reports/", app.reports_view, name="reports"),
    path("budgets/", app.budgets_view, name="budgets"),
    path("categories/", app.categories, name="categories"),
    path("categories/new/", app.category_edit, name="category_new"),
    path("categories/<int:pk>/", app.category_edit, name="category_edit"),
    path("categories/<int:pk>/delete/", app.category_delete, name="category_delete"),
    path("rules/", app.rules_list, name="rules"),
    path("rules/new/", app.rule_edit, name="rule_new"),
    path("rules/apply/", app.rules_apply, name="rules_apply"),
    path("rules/<int:pk>/", app.rule_edit, name="rule_edit"),
    path("rules/<int:pk>/delete/", app.rule_delete, name="rule_delete"),
    path("accounts/", app.accounts, name="accounts"),
    path("accounts/new/", app.account_edit, name="account_new"),
    path("accounts/<int:pk>/", app.account_edit, name="account_edit"),
    path("accounts/<int:pk>/delete/", app.account_delete, name="account_delete"),
    path("import/", app.import_sms, name="import"),
    path("messages/", app.messages_list, name="messages"),
    path("messages/<int:pk>/delete/", app.message_delete, name="message_delete"),
    path("messages/<int:pk>/share/", app.message_share, name="message_share"),
    # me
    path("setup/", me.setup, name="setup"),
    path("setup/devices/<int:pk>/revoke/", me.device_revoke, name="device_revoke"),
    path("setup/devices/<int:pk>/status/", me.device_status, name="device_status"),
    path("setup/shortcut/", me.shortcut_file, name="shortcut_file"),
    path("settings/", me.settings_view, name="settings"),
    path("settings/2fa/", me.twofa_setup, name="twofa_setup"),
    path("settings/2fa/disable/", me.twofa_disable, name="twofa_disable"),
    path("settings/export.csv", me.export_all, name="export_all"),
    path("settings/delete/", me.delete_account, name="delete_account"),
    path("security/", security.security_home, name="security"),
    path("security/sessions/<int:pk>/revoke/", security.session_revoke, name="session_revoke"),
    path("security/sessions/revoke-others/", security.sessions_revoke_others, name="sessions_revoke_others"),
    path("security/recovery-key/", security.recovery_key, name="recovery_key"),
    path("unlock/", security.unlock, name="unlock"),
    # operator
    path("staff/", staff.staff_home, name="staff"),
    path("staff/invites/", staff.invite_create, name="invite_create"),
    path("staff/invites/<int:pk>/revoke/", staff.invite_revoke, name="invite_revoke"),
    path("staff/users/<int:pk>/toggle/", staff.user_toggle, name="user_toggle"),
    path("staff/samples/<int:pk>/resolve/", staff.sample_resolve, name="sample_resolve"),
]
